[package]
name = "rebus"
version = "0.1.0"
authors = [
    "Alexander Meshcheryakov <freecoder.xx@gmail.com>"
]
edition = "2018"

[dependencies]
structopt = "0.2"
config = "0.9"
serde = { version = "1.0", features = ["derive"] }
dirs = "2.0"